config/routes.rb
Modsfortowns::Application.routes.draw do

  resources 'infos'
  resources 'categories'
  resources 'mods' do
    resources 'versions'
  end
  resources 'packs'
  resources :users
  resource :session, only: [:new, :create, :destroy]
  get 'signup' => 'users#new', as: :signup
  post 'register' => 'users#create', as: :register
  get 'login' => 'sessions#new', as: :login
  get 'logout' => 'sessions#destroy', as: :logout
  get '/activate/:activation_code' => 'users#activate', as: :activate, activation_code: nil

  root 'infos#index'

end

app/models/mod.rb
class Mod < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :description, presence:  true
  validates :user_id, presence: true
  validates :screenshot, presence: true
  validates :category_id, presence: true
  validates :status, presence: true, inclusion: {in: ['Concept', 'Developement', 'Complete', 'Inactive']}
  mount_uploader :screenshot, ScreenshotUploader
  belongs_to :user
  belongs_to :category
  has_many :versions
  after_create :set_author
  scope :latest, order: 'updated_at desc'
  scope :hottest, order: 'updated_at desc'
  def last_version
    self.versions.last if self.versions.length > 0
  end
  def tag
    "#{self.name} by #{self.user.name}"
  end
private
  def set_author
    if self.user
      self.user.update_attribute(:author, true)
    end
  end
end

app/controllers/mods_controller.rb
# Copyright (c) 2010 by Robert D. Cotey II
#    This file is part of coteyr_pack.
#
#    coteyr_pack is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    coteyr_pack is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with coteyr_pack.  If not, see <http://www.gnu.org/licenses/>.
class ModsController < ApplicationController
  include Restful
  def initialize
    super
    @skope = "Mod"
    @klass =  Mod
  end
  before_filter :set_page_title
  before_filter :find_categories, only: [:new, :create, :update, :edit]
  def index
    conditions = {}
    conditions.merge!({user_id: params[:user_id]}) if params[:user_id]
    conditions.merge!({category_id: params[:category_id]}) if params[:category_id]
    conditions.merge!({status: 'Complete'}) if params[:complete] and params[:complete].to_i == 1
    @mods = Mod.where(conditions)
    respond_to do |format|
      format.html {}
      format.json {
        render json: @mods.to_json(include: ['last_version', :category] )
      }
    end
  end
private
  def set_page_title
    mod = Mod.find params[:id] if params[:id]
    @page_title = mod.name if mod
    @page_title ||= 'Mods'
    @page_icon = 'font-eye-open'
  end
  def allowed_params
    params.require :mod
    params.permit mod: [:name, :description, :user_id, :screenshot, :screenshot_cache, :category_id, :status]
  end
  def find_categories
    @categories = Category.find :all
  end
end

app/helpers/mods_helper.rb
module ModsHelper
end

app/views/mods/_form.html.erb
<%= render "layouts/error_messages", target: @mod %>
<%= form_for @mod do |f| %>
  <%= field_set_tag 'mod' do %>
    <%= f.text_field :name %>
    <%= f.select :category_id, @categories.map { |c| [c.name, c.id] }, label: 'category' %>
    <%= f.select :status, ['Concept', 'Developement', 'Complete', 'Inactive'] %>
    <%= f.file_field :screenshot %>
    <%= f.hidden_field :screenshot_cache %>
    <%= f.text_area :description, class: 'mceEditor' %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.form_actions %>
  <% end %>
<% end %>

app/views/mods/_mod.html.erb
<tr>
   <td><%= mod.name %></td>
   <td><%= mod.user.name %></td>
   <td>
      <%= link_to 'edit', edit_mod_path(mod), class: 'btn btn-info' %>
      <%= link_to 'view', mod_path(mod), class: 'btn btn-info' %>
   </td>
</tr>

app/views/mods/_version.html.erb
<dt><%= version.mod.name %> version <%= version.number %> uploaded <%= time_ago_in_words version.created_at %> ago</dt>
<dd>
  <%= version.major_changes.html_safe %>
</dd>

app/views/mods/index.html.erb
<%= well 'mod', pad: false do %>
   <table class="table table-striped">
   <thead>
      <tr>
         <th>Name</th>
         <th>Author</th>
         <th></th>
      </tr>
   </thead>
   <tbody>
      <%= render partial: 'mod', collection: @mods %>
   </tbody>
</table>
<div class="center">
  <%= link_to 'add new', new_mod_path %>
</div>

<% end %>

app/views/mods/show.html.erb
<%= row do %>
  <%= well 'Screenshot', size: 6, pad: false do %>
    <%= image_tag @mod.screenshot.shot.url, class: 'span12' %>
    <div class="clear">
      <p class="center">
        <%= button 'view full size', @mod.screenshot.big.url, type: 'info' %>
      </p>
    </div>
  <% end %>
  <%= well 'Details', size: 6 do %>
    <div style="min-height: 334px">
      <dl class="dl-horizontal">
        <dt>Name</dt>
        <dd><%= @mod.name %></dd>
        <dt>Author</dt>
        <dd><%= @mod.user.name %></dd>
        <dt>First Uploaded</dt>
        <dd><%= time_ago_in_words @mod.created_at %> ago</dd>
        <dt>Last updated</dt>
        <dd><%= time_ago_in_words @mod.updated_at %> ago</dd>
        <dt>Versions</dt>
        <dd><%= @mod.versions.count %></dd>
        <dt>Latest Version</dt>
        <dd><% if @mod.versions.length > 0 %><%= @mod.last_version.number %><% end %></dd>
        <dt>Included In Packs</dt>
        <dd>0</dd>
        <dt>Populatity Rating</dt>
        <dd>0</dd>
      </dl>
      <% if @mod.versions.length > 0 %>
        <p class="center">
          <%= button 'Download Now', @mod.last_version.download.url, type: 'success', icon: 'icon-download'  %>
        </p>
        <p class="center">
          <%= button 'View Old Versions', mod_versions_path(@mod), type: 'info' %>
        </p>
      <% else %>
        <p class="center">
          <%= button 'Upload a Version', new_mod_version_path(@mod), type: 'info' %>
        </p>
      <% end %>
    </div>
  <% end %>
<% end %>
<%= row do %>
  <%= well 'Description', size: 8 do %>
    <%= @mod.description.html_safe %>
  <% end %>
  <%= well 'Changelog', size: 4 do %>
    <dl>
      <%= render partial: 'version', collection: @mod.versions %>
    </dl>
  <% end %>
<% end %>