config/routes.rb
Modsfortowns::Application.routes.draw do

  resources 'infos'
  resources 'categories'
  resources 'mods' do
    resources 'versions'
  end
  resources 'packs'
  resources :users
  resource :session, only: [:new, :create, :destroy]
  get 'signup' => 'users#new', as: :signup
  post 'register' => 'users#create', as: :register
  get 'login' => 'sessions#new', as: :login
  get 'logout' => 'sessions#destroy', as: :logout
  get '/activate/:activation_code' => 'users#activate', as: :activate, activation_code: nil

  root 'infos#index'

end

app/models/version.rb
class Version < ActiveRecord::Base
  validates :number, presence: true
  validates :mod_id, presence: true
  validates :major_changes, presence: true
  validates :download, presence: true
  mount_uploader :download, ModUploader
  belongs_to :mod
  default_scope order: 'created_at desc'
end

app/controllers/versions_controller.rb
# Copyright (c) 2010 by Robert D. Cotey II
#    This file is part of coteyr_pack.
#
#    coteyr_pack is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    coteyr_pack is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with coteyr_pack.  If not, see <http://www.gnu.org/licenses/>.
class VersionsController < ApplicationController
  include Restful
  def initialize
    super
    @skope = "@mod.versions"
    @klass =  Version
  end
  before_filter :set_page_title
  before_filter :find_mod
private
  def set_page_title
    @page_title = 'Versions'
    @page_icon = 'font-list-ul'
  end
  def allowed_params
    params.require(:version)
    params.permit(version: [:id, :download, :number, :mod_id, :major_changes])
  end
  def find_mod
    @mod = Mod.find params[:mod_id]
  end
end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/views/versions/_form.html.erb
<%= render "layouts/error_messages", target: @version %>
<%= form_for [@mod, @version], html: {multipart: true} do |f| %>
  <%= field_set_tag 'version' do %>
    <%= f.hidden_field :mod_id, value: @mod.id %>
    <%= f.text_field :number %>
    <%= f.file_field :download %>
    <%= f.text_area :major_changes, class: 'mceEditor' %>
    <%= f.form_actions %>
  <% end %>
<% end %>

app/views/versions/_version.html.erb
<tr>
   <td><%= version.mod.name %></td>
   <td><%= version.number %></td>
   <td>
      <%= link_to 'edit', edit_mod_version_path(@mod, version), class: 'btn btn-info' %>
      <%= link_to 'view', mod_version_path(@mod, version), class: 'btn btn-info' %>
   </td>
</tr>

app/views/versions/index.html.erb
<%= well 'version', pad: false do %>
   <table class="table table-striped">
   <thead>
      <tr>
         <th>Mod</th>
         <th>Number</th>
         <th></th>
      </tr>
   </thead>
   <tbody>
      <%= render partial: 'version', collection: @versions %>
   </tbody>
</table>
<div class="center">
  <%= link_to 'add new', new_mod_version_path(@mod) %>
</div>

<% end %>

app/views/versions/show.html.erb
<div class="version">
  <%= @version.id %>
</div>