config/routes.rb
Modsfortowns::Application.routes.draw do

  resources 'infos'
  resources 'categories'
  resources 'mods' do
    resources 'versions'
  end
  resources 'packs'
  resources :users
  resource :session, only: [:new, :create, :destroy]
  get 'signup' => 'users#new', as: :signup
  post 'register' => 'users#create', as: :register
  get 'login' => 'sessions#new', as: :login
  get 'logout' => 'sessions#destroy', as: :logout
  get '/activate/:activation_code' => 'users#activate', as: :activate, activation_code: nil

  root 'infos#index'

end

app/models/pack.rb
class Pack < ActiveRecord::Base
  validates :user_id, presence: true
  validates :title, presence: true, uniqueness: true
  validates :screenshot, presence: true
  validates :status, presence: true, inclusion: {in: ['Concept', 'Developement', 'Complete', 'Inactive']}
  mount_uploader :screenshot, ScreenshotUploader
  belongs_to :user
  after_create :set_author
  scope :latest, order: 'updated_at desc'
  scope :hottest, order: 'updated_at desc'
  def tag
    "#{self.title} by #{self.user.name}"
  end
private
  def set_author
    if self.user
      self.user.update_attribute(:author, true)
    end
  end
end

app/controllers/packs_controller.rb
# Copyright (c) 2010 by Robert D. Cotey II
#    This file is part of coteyr_pack.
#
#    coteyr_pack is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    coteyr_pack is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with coteyr_pack.  If not, see <http://www.gnu.org/licenses/>.
class PacksController < ApplicationController
  include Restful
  def initialize
    super
    @skope = "Pack"
    @klass =  Pack
  end
  before_filter :set_page_title
private
  def set_page_title
    @page_title = 'Mod Packs'
    @page_icon = 'font-list-ul'
  end
  def allowed_params
    params.require(:pack)
    params.permit(pack: [:title, :user_id, :screenshot, :screenshot_cache, :status])
  end
end

app/helpers/packs_helper.rb
module PacksHelper
end

app/views/packs/_form.html.erb
<%= render "layouts/error_messages", target: @pack %>
<%= form_for @pack do |f| %>
  <%= field_set_tag 'pack' do %>
    <%= f.text_field :title %>
    <%= f.select :status, ['Concept', 'Developement', 'Complete', 'Inactive'] %>
    <%= f.file_field :screenshot %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.form_actions %>
  <% end %>
<% end %>

app/views/packs/_pack.html.erb
<tr>
   <td><%= pack.title %></td>
   <td><%= pack.user.name %></td>
   <td>
      <%= link_to 'edit', edit_pack_path(pack), class: 'btn btn-info' %>
      <%= link_to 'view', pack_path(pack), class: 'btn btn-info' %>
   </td>
</tr>

app/views/packs/index.html.erb
<%= well 'pack', pad: false do %>
   <table class="table table-striped">
   <thead>
      <tr>
         <th>Name</th>
         <th>Author</th>
         <th></th>
      </tr>
   </thead>
   <tbody>
      <%= render partial: 'pack', collection: @packs %>
   </tbody>
</table>
<div class="center">
  <%= link_to 'add new', new_pack_path %>
</div>

<% end %>

app/views/packs/show.html.erb
<%= row do %>
  <%= well 'Screenshot', size: 6, pad: false do %>
    <%= image_tag @pack.screenshot.shot.url, class: 'span12' %>
    <div class="clear">
      <p class="center">
        <%= button 'view full size', @pack.screenshot.big.url, type: 'info' %>
      </p>
    </div>
  <% end %>
<% end %>
<h2>This section of the site is incomplete </h2>