config/routes.rb
Modsfortowns::Application.routes.draw do

  resources 'infos'
  resources 'categories'
  resources 'mods' do
    resources 'versions'
  end
  resources 'packs'
  resources :users
  resource :session, only: [:new, :create, :destroy]
  get 'signup' => 'users#new', as: :signup
  post 'register' => 'users#create', as: :register
  get 'login' => 'sessions#new', as: :login
  get 'logout' => 'sessions#destroy', as: :logout
  get '/activate/:activation_code' => 'users#activate', as: :activate, activation_code: nil

  root 'infos#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
end

app/controllers/categories_controller.rb
# Copyright (c) 2010 by Robert D. Cotey II
#    This file is part of coteyr_pack.
#
#    coteyr_pack is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    coteyr_pack is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with coteyr_pack.  If not, see <http://www.gnu.org/licenses/>.
class CategoriesController < ApplicationController
  include Restful
  def initialize
    super
    @skope = "Category"
    @klass =  Category
  end
  before_filter :set_page_title
private
  def set_page_title
    @page_title = 'Categories'
    @page_icon = 'font-list-ul'
  end
  def allowed_params
    params.require(:category)
    params.permit(category: [:id, :name, :description])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<tr>
   <td><%= category.name %></td>
   <td>
      <%= link_to 'edit', edit_category_path(category), class: 'btn btn-info' %>
      <%= link_to 'view', category_path(category), class: 'btn btn-info' %>
   </td>
</tr>

app/views/categories/_form.html.erb
<%= render "layouts/error_messages", target: @category %>
<%= form_for @category do |f| %>
  <%= field_set_tag 'category' do %>
    <%= f.text_field :name %>
    <%= f.text_area :description, class: 'mceEditor' %>
    <%= f.form_actions %>
  <% end %>
<% end %>

app/views/categories/edit.html.erb
<%= render partial: 'form' %>

app/views/categories/index.html.erb
<%= well 'category', pad: false do %>
   <table class="table table-striped">
   <thead>
      <tr>
         <th>Name</th>
         <th></th>
      </tr>
   </thead>
   <tbody>
      <%= render partial: 'category', collection: @categories %>
   </tbody>
</table>
<div class="center">
  <%= link_to 'add new', new_category_path %>
</div>

<% end %>

app/views/categories/new.html.erb
<%= render partial: 'form' %>

app/views/categories/show.html.erb
<div class="category">
  <%= @category.id %>
</div>